#!/usr/bin/env python3
"""
Recolorable livery templates: a factory spec with {{param}} holes, a parameter schema, and the
one code path that turns (template, params) into a texture. Used three ways:

  1. Pack liveries (starters, Gun Game kits) are template instances listed in
     liveries/templates/instances.json; `generate` writes them out as ordinary specs in
     liveries/specs/ (marked "template"/"params") that the factory builds like any other.
  2. The dashboard's "Recolor + text" calls `render` (or render_bytes() from Python) with the
     pilot's choices. Same validation, same painter, same output contract (native size/format,
     under 1.5 MB), so a pilot's custom livery is indistinguishable from a pack one.
  3. `list --json` prints the schema the dashboard form is built from.

  python tools/livery_templates.py list [--json]
  python tools/livery_templates.py generate            rewrite every instance spec
  python tools/livery_templates.py check               instances.json and specs/ agree
  python tools/livery_templates.py render --template f16_speedline \
      --params '{"base": "#112233", "title": "STEVE"}' --out out.webp [--seed 7]

Template file (liveries/templates/<id>.json):
  {
    "id": "f16_speedline", "aircraft": "f16", "name": "Speedline", "description": "...",
    "params": {
      "base":  {"type": "color", "default": "#8f959c", "label": "Body"},
      "title": {"type": "text",  "default": "FINSONLY", "max": 10, "label": "Name on the intakes"},
      "tail":  {"type": "tail",  "default": "N4800F", "label": "Tail number"},
      "rough": {"type": "int",   "default": 14, "min": 6, "max": 160, "label": "Roughness"}
    },
    "spec": { ...a normal factory spec without id/name/seed... }
  }

Inside "spec", a string that is exactly "{{p}}" becomes the parameter's value (any type); a
filter tweaks a colour: "{{p|dark:0.4}}" mixes 40% toward black, "{{p|light:0.3}}" 30% toward
white, "{{p|alpha:0.5}}" sets alpha. Text may embed holes: "{{tail}}-X".
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import livery_common as lc  # noqa: E402

TPL_DIR = lc.LIV / "templates"
INSTANCES = TPL_DIR / "instances.json"
SPEC_DIR = lc.LIV / "specs"

# Glyphs every bundled font (Anton, Bungee) draws. Uppercased before the check.
TEXT_CHARS = re.compile(r"[A-Z0-9 .!&'\-]*")
TAIL_RE = re.compile(r"[A-Z0-9][A-Z0-9\-]{0,6}")
COLOR_RE = re.compile(r"#[0-9a-fA-F]{6}")
HOLE = re.compile(r"\{\{(\w+)(?:\|(\w+):([0-9.]+))?\}\}")
GENERATED_NOTE = ("generated by tools/livery_templates.py from liveries/templates/instances.json; "
                  "edit that file and run `generate`, not this one")


class ParamError(ValueError):
    pass


# ----------------------------------------------------------------------------------- loading
def load_template(tid: str) -> dict:
    p = TPL_DIR / f"{tid}.json"
    if not re.fullmatch(r"[a-z0-9_]+", tid) or not p.is_file():
        raise ParamError(f"no template '{tid}'")
    t = json.loads(p.read_text(encoding="utf-8"))
    if t.get("id") != tid:
        raise ParamError(f"{p.name}: id must equal the file name")
    return t


def all_templates() -> list[dict]:
    return [load_template(p.stem) for p in sorted(TPL_DIR.glob("*.json"))
            if p.name != "instances.json"]


# ----------------------------------------------------------------------------------- params
def clean_params(tpl: dict, params: dict | None) -> dict:
    """Validate pilot input against the schema, fill defaults. Raises ParamError with a
    message fit to show a user. Unknown keys are rejected (the form can't send junk)."""
    params = dict(params or {})
    schema = tpl["params"]
    extra = set(params) - set(schema)
    if extra:
        raise ParamError(f"unknown parameter(s): {', '.join(sorted(extra))}")
    out = {}
    for k, sch in schema.items():
        v = params.get(k, sch["default"])
        t = sch["type"]
        if t == "color":
            if not isinstance(v, str) or not COLOR_RE.fullmatch(v):
                raise ParamError(f"{k}: colour must look like #rrggbb")
            v = v.lower()
        elif t == "text":
            if not isinstance(v, str):
                raise ParamError(f"{k}: must be text")
            v = " ".join(v.upper().split())
            if not v and not sch.get("allow_empty"):
                raise ParamError(f"{k}: can't be empty")
            if len(v) > int(sch.get("max", 12)):
                raise ParamError(f"{k}: at most {sch.get('max', 12)} characters")
            if not TEXT_CHARS.fullmatch(v):
                raise ParamError(f"{k}: letters, digits, space and . ! & ' - only")
        elif t == "tail":
            if not isinstance(v, str):
                raise ParamError(f"{k}: must be text")
            v = v.upper().strip()
            if not TAIL_RE.fullmatch(v):
                raise ParamError(f"{k}: 1-7 letters/digits/dashes, starting with a letter or digit")
        elif t == "int":
            if isinstance(v, bool) or not isinstance(v, int):
                raise ParamError(f"{k}: must be a whole number")
            if not int(sch["min"]) <= v <= int(sch["max"]):
                raise ParamError(f"{k}: between {sch['min']} and {sch['max']}")
        else:
            raise ParamError(f"{k}: template declares unknown type {t!r}")
        out[k] = v
    return out


def _mix(hexc, target, f):
    c = [int(hexc[i:i + 2], 16) for i in (1, 3, 5)]
    m = [round(a + (target - a) * f) for a in c]
    return "#" + "".join(f"{max(0, min(255, x)):02x}" for x in m)


def _fill_hole(m, params):
    k, flt, arg = m.group(1), m.group(2), m.group(3)
    if k not in params:
        raise ParamError(f"template hole {{{{{k}}}}} has no parameter")
    v = params[k]
    if flt:
        if not (isinstance(v, str) and COLOR_RE.fullmatch(v)):
            raise ParamError(f"filter on non-colour {{{{{k}}}}}")
        f = float(arg)
        if flt == "dark":
            return _mix(v, 0, f)
        if flt == "light":
            return _mix(v, 255, f)
        if flt == "alpha":
            return v + f"{round(max(0.0, min(1.0, f)) * 255):02x}"
        raise ParamError(f"unknown filter {flt}")
    return v


def _subst(node, params):
    if isinstance(node, dict):
        return {k: _subst(v, params) for k, v in node.items()}
    if isinstance(node, list):
        return [_subst(v, params) for v in node]
    if isinstance(node, str):
        whole = HOLE.fullmatch(node)
        if whole:
            return _fill_hole(whole, params)
        return HOLE.sub(lambda m: str(_fill_hole(m, params)), node)
    return node


def instantiate(tpl: dict, params: dict | None, *, sid="custom", name="Custom livery",
                seed=None) -> dict:
    """-> a validated factory spec."""
    import livery_factory as F
    p = clean_params(tpl, params)
    body = _subst(tpl["spec"], p)
    if seed is None:
        # deterministic per (template, params): the same choices always give the same pixels
        seed = int(hashlib.sha256(json.dumps([tpl["id"], p], sort_keys=True).encode())
                   .hexdigest()[:8], 16)
    spec = {"id": sid, "aircraft": tpl["aircraft"], "name": name,
            "credits": "FINSONLY Livery Factory", "seed": int(seed), **body,
            "template": tpl["id"], "params": p}
    return F.validate_spec(spec)


def render_bytes(tid: str, params: dict | None, seed=None):
    """(template id, pilot params) -> list of (filename suffix, bytes, note). One entry for F-16
    and 757 ("" suffix), two for the Rafale ("_main", "_spec"). Raises ParamError."""
    import livery_factory as F
    tpl = load_template(tid)
    spec = instantiate(tpl, params, seed=seed)
    out = []
    for img, path in zip(F.render(spec), F.out_paths(spec)):
        if spec["aircraft"] == "rafale" and path.stem.endswith("_spec"):
            out.append(("_spec", F._encode_lossless_webp(img), "webp lossless"))
            continue
        ac = lc.AIRCRAFT[spec["aircraft"]]
        data, note = lc.encode(img, ac["fmt"], ac.get("quality", 88))
        out.append(("_main" if spec["aircraft"] == "rafale" else "", data, note))
    return out


# ----------------------------------------------------------------------------------- instances
def load_instances() -> list[dict]:
    data = json.loads(INSTANCES.read_text(encoding="utf-8"))
    return data["instances"]


def instance_spec(inst: dict) -> dict:
    tpl = load_template(inst["template"])
    spec = instantiate(tpl, inst.get("params"), sid=inst["id"], name=inst["name"],
                       seed=inst["seed"])
    spec["_generated"] = GENERATED_NOTE
    for k in ("listed", "catalog"):
        if k in inst:
            spec[k] = inst[k]
    return spec


def _dump(spec) -> str:
    order = ["_generated", "id", "aircraft", "name", "credits", "seed", "template", "params",
             "listed", "catalog", "base", "rafale", "layers", "finish"]
    ordered = {k: spec[k] for k in order if k in spec}
    ordered.update({k: v for k, v in spec.items() if k not in ordered})
    lines = ["{"]
    items = list(ordered.items())
    for i, (k, v) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        if k == "layers":
            lines.append('  "layers": [')
            for j, L in enumerate(v):
                lines.append("    " + json.dumps(L) + ("," if j < len(v) - 1 else ""))
            lines.append("  ]" + comma)
        else:
            lines.append(f"  {json.dumps(k)}: {json.dumps(v)}{comma}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def generate() -> list[Path]:
    written = []
    for inst in load_instances():
        p = SPEC_DIR / f"{inst['id']}.json"
        text = _dump(instance_spec(inst))
        if not p.exists() or p.read_text(encoding="utf-8") != text:
            p.write_text(text, encoding="utf-8")
            written.append(p)
    return written


def check() -> list[str]:
    errs = []
    ids = [i["id"] for i in load_instances()]
    if len(ids) != len(set(ids)):
        errs.append("duplicate instance ids")
    for inst in load_instances():
        p = SPEC_DIR / f"{inst['id']}.json"
        try:
            want = _dump(instance_spec(inst))
        except Exception as e:  # noqa: BLE001
            errs.append(f"{inst['id']}: {e}")
            continue
        if not p.exists():
            errs.append(f"{inst['id']}: spec missing (run generate)")
        elif p.read_text(encoding="utf-8") != want:
            errs.append(f"{inst['id']}: spec out of date (run generate)")
    return errs


def schema() -> list[dict]:
    """What the dashboard needs to draw a form: template id, aircraft, name, description,
    params (type, default, label, limits). Gun Game kits are mode paints, not pilot templates."""
    out = []
    for t in all_templates():
        if t.get("pilot", True):
            out.append({k: t[k] for k in ("id", "aircraft", "name", "description", "params")})
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    sub = ap.add_subparsers(dest="cmd", required=True)
    ls = sub.add_parser("list")
    ls.add_argument("--json", action="store_true")
    sub.add_parser("generate")
    sub.add_parser("check")
    r = sub.add_parser("render")
    r.add_argument("--template", required=True)
    r.add_argument("--params", default="{}", help="JSON object")
    r.add_argument("--out", required=True, help="output path; the Rafale writes <stem>_main/_spec")
    r.add_argument("--seed", type=int)
    a = ap.parse_args(argv)
    if a.cmd == "list":
        s = schema()
        if a.json:
            print(json.dumps(s, indent=1))
        else:
            for t in s:
                print(f"{t['id']:22s} {t['aircraft']:7s} {t['name']}  ({', '.join(t['params'])})")
    elif a.cmd == "generate":
        for p in generate():
            print(p.relative_to(lc.ROOT))
    elif a.cmd == "check":
        errs = check()
        print("OK" if not errs else "\n".join(errs))
        sys.exit(1 if errs else 0)
    else:
        try:
            parts = render_bytes(a.template, json.loads(a.params), a.seed)
        except (ParamError, json.JSONDecodeError) as e:
            print(json.dumps({"ok": False, "error": str(e)}))
            sys.exit(2)
        out = Path(a.out)
        res = []
        for suffix, data, note in parts:
            p = out.with_name(out.stem + suffix + out.suffix) if suffix else out
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_bytes(data)
            res.append({"path": str(p), "bytes": len(data), "note": note,
                        "sha256": hashlib.sha256(data).hexdigest()})
        print(json.dumps({"ok": True, "files": res}))


if __name__ == "__main__":
    main()
